notifications:
  irc:
    channels:
      - "chat.freenode.net#noosfero"
      - "chat.freenode.net#noosfero-br"
    template:
      - "%{repository_slug} %{branch} %{commit} %{commit_subject} - %{result} %{build_url}"

# trusty constainers take more time to start
#dist: trusty

language: ruby
rvm:
  - 2.2
  # ruby 2.3 works but isn't stable on travis

cache: bundler

addons:
  apt:
    packages:
      - tango-icon-theme
      - pidgin-data
  artifacts:
    paths:
      - $(ls tmp/artifact* | tr "\n" ":")

# workaround for https://github.com/travis-ci/travis-ci/issues/4536
before_install:
  - export GEM_HOME=$PWD/vendor/bundle/ruby/2.2.0
  - gem install bundler

before_script:
  - mkdir -p tmp/{pids,cache} log cache
  - script/noosfero-plugins disableall
  #- bundle exec rake makemo &>/dev/null
# database
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database myapp_test;' -U postgres
  - bundle exec rake db:schema:load
  - bundle exec rake db:migrate &>/dev/null

env:
  - TASK=test:api
  - TASK=test:units
  - TASK=test:functionals
  - TASK=test:integration
  - SLICE=1/2 TASK=cucumber LANG=en
  - SLICE=2/2 TASK=cucumber LANG=en
  - SLICE=1/4 TASK=selenium
  - SLICE=2/4 TASK=selenium
  - SLICE=3/4 TASK=selenium
  - SLICE=4/4 TASK=selenium
  - SLICE=1/5 TASK=test:noosfero_plugins BUNDLE_OPTS=install
  - SLICE=2/5 TASK=test:noosfero_plugins BUNDLE_OPTS=install
  - SLICE=3/5 TASK=test:noosfero_plugins BUNDLE_OPTS=install
  - SLICE=4/5 TASK=test:noosfero_plugins BUNDLE_OPTS=install
  - SLICE=5/5 TASK=test:noosfero_plugins BUNDLE_OPTS=install

script:
  - bundle exec rake $TASK

