#!/usr/bin/env ruby

require 'daemons'
require 'optparse'

NOOSFERO_ROOT = File.expand_path(File.dirname(__FILE__) + '/../../../')

Daemons.run_proc('hub') do
  require NOOSFERO_ROOT + '/config/environment'
  CommunityHubPlugin::Hub.start_listen
end
