#!/usr/bin/env ruby

require 'daemons'
require 'optparse'

NOOSFERO_ROOT = File.expand_path(File.dirname(__FILE__) + '/../../../')
require NOOSFERO_ROOT + '/config/environment'

Daemons.run_proc('hub') do
  unless ENV['PROXY'].blank?
    ENV['NO_PROXY'] ||= 'localhost'
    require 'proxifier/env'
  end
  CommunityHubPlugin::Listener.run
end
